Added layouts directory to avoid error when generating site
Hugo ouputs an error like:

ERROR: 2014/11/19 Walker:  lstat /path/to/HugoBasicExample/layouts: no such file or directory

when testing a new theme against this repo, unless the layouts folder is created first

Tested with hugo built from commit master (on commit 728d0fa32cb666264045783518cc6ded5c78f246)